SRC=$(wildcard *.mon)
O_SRC=$(sort ${SRC})
F9DASM=f9dasm -noconv -noflex

$(warning ${O_SRC} )

%.hex : %.mon
	sed -e '/*/d' -e '/^$$/d' -e 's/-/:/g' $< > $@

%.bin : %.hex
	xxd -r -seek -$$((16#8000)) -g1 -c8 $< > $@

%.hexdump : %.bin
	xxd $< > $@

#%.info : %.bin
#	echo "FILE \"$<\" E000" > $@

%9619.info :
	echo "## This file is automatically generated. Do not edit. ##\n" > $@.tmp
	cat  *9619.info >> $@.tmp
	mv   $@.tmp $@

%9609.info :
	echo "## This file is automatically generated. Do not edit. ##\n" > $@.tmp
	cat  *9609.info >> $@.tmp
	mv   $@.tmp $@

%9609.asm : %9609.info U22_9609.bin U23_9609.bin
	$(F9DASM) -info $< -out $@

%9619.asm : %9619.info U7_9619.bin U17_9619.bin
	$(F9DASM) -info $< -out $@

%.asm : %.info %.bin
	$(F9DASM) -info $< -out $@

help : 
	echo "Uses xxd and f9dasm to disassemble 6809 code as read by the \n\
	 Apple II monitor and exported to .mon files. Try: \n\
	     make EPROM_9619.asm \n     make EPROM_9609.asm\n     make all \n\
	     make U7_9619.hexdump\n     make U7_9619.asm"


all : EPROM_9619.asm EPROM_9609.asm

clean:
	rm -f *hex
	rm -f *hexdump
	rm -f *bin
	rm -f *0bin
#	rm -f *info
	rm -f *tmp
	rm -f EPROM_9609.info EPROM_9619.info
	rm -f *asm

.PHONY: clean all 9609 9619 help

.SECONDARY: %.hex
